package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"

	"encore.app/user"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input *user.CreateUserParams) (*user.User, error) {
	return user.CreateUser(ctx, input)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*user.User, error) {
	resp, err := user.List(ctx)
	if err != nil {
		return nil, err
	}
	return resp.Users, nil
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, email string) (*user.User, error) {
	return user.GetUser(ctx, email)
}

// Mutation returns generated.MutationResolver implementation.
// Remove the duplicate declaration of the Mutation method.
// func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
// func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }
